services:
  - type: web
    name: podvision-backend
    runtime: docker
    # buildCommand and startCommand are handled by Dockerfile
    rootDir: backend
    healthCheckPath: /
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: podvision-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: podvision-redis
          property: connectionString
  - type: worker
    name: podvision-celery-worker
    runtime: docker
    # buildCommand and startCommand are handled by Dockerfile
    rootDir: backend
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: podvision-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: podvision-redis
          property: connectionString
  - type: redis
    name: podvision-redis
    ipAllowList: [] # Allow all connections (for testing, restrict in production)
    maxmemoryPolicy: noeviction
